### PR TITLE
Provide option to ignore certain classes

### PR DESCRIPTION
**Pull request by rikki-iki**
Needed to be able to ignore elements based on their class or their parents class

### CODE REVIEW

**Comment by ndabas** [comment]
This is not needed. You already have this functionality in the current version because you can specify exclusions using the jQuery selector syntax. For example, to ignore all H3 elements with the class 'ignored', you can do this:

```
$("#toc").toc({content: "div.container", headings: "h2,h3:not('.ignored'),h4"})
```

You can also use data attributes:

```
<ol data-toc="div.container" data-toc-headings="h2,h3:not('.ignored'),h4"></ol>
```

The documentation makes it pretty clear that you can use any valid jQuery selectors in this context.

**Comment by rikki-iki** [comment]
Oh of course!! lol sorry I didn't even think of that. 
My use case needs the parents part anyway so not a complete waste of time, but it probably is an edge case.

**Comment by ndabas** [comment]
Sure, no problem!

You could also pass in a jQuery selector or selection object to the `content` argument, if you can craft your exclusions that way. This library looks for the headings within the `content` selection so that should do the trick if you want to ignore a container class or whatever from all headings.

**Comment by ndabas** [comment]
Just thought I'd mention that I am closing this now, because like you said it's an edge case, and being minimal is one of the design goals of this library.

**Pull request closed without merging**
