### PR TITLE
feature: add headings numbering

### PR DESCRIPTION
**Pull request by bodik**
feature will add headings numbering for better orientation on the page and TOC

### CODE REVIEW

**Comment by ndabas** [comment]
Thank you for your effort; however, I will not merge this PR because toc is supposed to be minimal, and the feature you want can be implemented using just CSS, no JS needed.

There is an example in [this answer on StackOverflow](https://stackoverflow.com/a/4098296/1292105).

**Comment by bodik** [comment]
ok thanks for reply, but note that adding numbering is done to the actual headings too and that cannot be done without JS.

**Comment by ndabas** [comment]
If you're adding numbers to the headings -- that should be a separate plugin anyway because doing that is not in the scope of a TOC-generation plugin.

I believe it should be possible to achieve that as well using just CSS, as CSS counters are not tied to lists or list items, and can be used with any element.

**Comment by bodik** [comment]
sounds very reasonable, thank you for your time

**Pull request closed without merging**
